apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
  namespace: default
  labels:
    app: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-service
          image: kubernetes.docker.internal:5000/pheodor/dummy-web-app:latest
          ports:
            - containerPort: 7070
              protocol: TCP
      restartPolicy: Always
